name: PAS_sim
channels:
  - conda-forge
  - defaults
  - willkessler
dependencies:
  - python=3.9
  - jupyter
  - notebook
  - numpy
  - matplotlib
  - scipy
  - casadi
  - scikit-learn
  - jupytergraffiti
  - pandas
  - seaborn
  - h5py
  - control
  - pygame
  - black
